Android update to the latest gms:play-services-ads:20.5.0
invertase/react-native-google-ads pull request #32
Opened 2021-12-11 12:04 UTC by Mikenso

### Description

Android Update Banner, Interstitial, Rewarded add to be compitable with com.google.android.gms:play-services-ads:20.5.0

2021-12-11 12:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/react-native-google-ads?pullRequest=32) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/react-native-google-ads?pullRequest=32) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/react-native-google-ads?pullRequest=32) it.</sub>

2021-12-11 14:53 UTC, mikehardy commented
Oh fantastic! That was next up on the todo list and it appears you have nailed it! Is this a breaking change? I did not see any changes to the javsascript layer so this appears to be all on the native side. Is that a correct guess? I have not reviewed though - just skimmed really quickly before approving the CI run

Can you sign the CLA agreement as well? Excited to move quickly on this one, and I really appreciate that you posted this

2021-12-11 16:05 UTC, RodolfoGS commented
`onAdLeftApplication` will be removed? So, we'll not be able to know when a user left the app after tapped on an ad?

2021-12-11 16:08 UTC, mikehardy commented
@RodolfoGS check the underlying SDK docs for reference https://developers.google.com/admob/android/migration
what do they say on the matter?

2021-12-11 16:14 UTC, RodolfoGS commented
Mmm yes, I see, _Leave application callback removal_. Ok, thanks for the clarification!

2021-12-11 16:19 UTC, mikehardy commented
no problem - I have not read it much myself so I was not actually sure, but I had the link handy ;-). Cheers

2021-12-11 16:20 UTC, mikehardy commented
I marked this as a breaking change (with a title update on the PR including `!`) and that means we need to generate an excellent note for library consumers indicating what the breaking change(s) is/are, and how they need to react.

It seems like this one might simply be:

BREAKING CHANGE: onAdLeftApplication is removed from the underlying SDK, there is no replacement

2021-12-11 16:41 UTC, mikehardy commented
@Mikenso also needs a bump to compileSdkVersion to 31:

```
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.
     AAR metadata file: /Users/runner/.gradle/caches/transforms-3/4739effbb596877ca3318d6c0a41cf71/transformed/work-runtime-2.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.
```

BREAKING CHANGE: compileSdkVersion now 31, change your app android build.gradle to 31 if you have not already

2021-12-11 16:45 UTC, mikehardy commented
@Mikenso run google java formatter locally and commit the result, it will fix the lint errors:

```

2021-12-11 16:48 UTC, mikehardy requested changes
- lint errors
- example app update to compileSdkVersion 31
- needs a crystal clear description of all breaking changes, to help app developers deal with the changes

2021-12-11 17:38 UTC, dylancom commented
I think that also here setting testDevices has to move to the overall configuration instead of per ad. And so it has to be set in: https://github.com/invertase/react-native-google-ads/blob/9569b98768cacd3f0d3e95b7b44d15d20e59681a/android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsModule.java

Besides that the key "testDevices" became: "testDeviceIdentifiers".

So this PR should match with setting test devices as follow:
`admob().setRequestConfiguration({testDeviceIdentifiers: ["EMULATOR"]});`

2021-12-11 19:00 UTC, mikehardy commented
Agreed with Dylan's comment on making sure the test device stuff is in harmony with iOS changes as mentioned, thanks for the review Dylan

2021-12-12 12:02 UTC, Mikenso commented
Hi @mikehardy, @dylancom, thanks for review

Where do I need to specify breaking changes?
It would be:

### BREAKING CHANGES:
- compileSdkVersion now 31, change your app android build.gradle to 31 if you have not already. Note that JDK11 is required for stable compilation on compileSdkVersion 31, JDK8 has internal compiler errors with SDK31
- onAdLeftApplication is removed from the underlying SDK, there is no replacement
- Smart banner ads are deprecated in favor of adaptive banner ads.

2021-12-12 13:16 UTC, mikehardy requested changes
Starting to look good - I still need to do a deeper look (in progress) but here's the results of a surface level scan - simple item of annotation style

2021-12-12 13:16 UTC, mikehardy commented on android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java
> +import org.jetbrains.annotations.NotNull;
Please use the androidx annotations, you already have `androidx-annotation.NonNull` above, no need for jetbrains NotNull as well 
```suggestion
```

2021-12-12 13:16 UTC, mikehardy commented on android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java
> +          public void onAdFailedToLoad(@NonNull @NotNull LoadAdError loadAdError) {
```suggestion
          public void onAdFailedToLoad(@NonNull LoadAdError loadAdError) {
```

2021-12-12 13:16 UTC, mikehardy commented on android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsInterstitialModule.java
> +import org.jetbrains.annotations.NotNull;
same - stick with androidx annotations
```suggestion
```

2021-12-12 13:16 UTC, mikehardy commented on android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsInterstitialModule.java
> +                public void onAdLoaded(@NonNull @NotNull InterstitialAd interstitialAd) {
```suggestion
                public void onAdLoaded(@NonNull InterstitialAd interstitialAd) {
```

2021-12-12 13:16 UTC, mikehardy commented on android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsInterstitialModule.java
> +                public void onAdFailedToLoad(@NonNull @NotNull LoadAdError loadAdError) {
```suggestion
                public void onAdFailedToLoad(@NonNull LoadAdError loadAdError) {
```

2021-12-12 13:20 UTC, mikehardy commented
Looks like it needs either `yarn lint:prettier:fix` or `yarn:eslint:fix` as well. The lint tasks need to pass

```

$ yarn lint:js && yarn lint:android && yarn lint:ios:check
$ eslint lib/ --ext .js,.jsx,.ts,.tsx --max-warnings=0

/home/runner/work/react-native-google-ads/react-native-google-ads/lib/index.d.ts
Error:   123:24  error  Delete `····`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

2021-12-12 14:02 UTC, merged

2021-12-12 14:03 UTC, mikehardy reviewed
looked good - I confirmed smart banners were gone on ios side as well, and left-app event was also gone on ios, so API is now consistent across platforms with both up to date on SDKs
This looks like a solid forward port, thank you

2021-12-12 15:19 UTC, mikehardy commented
:tada: This PR is included in version 3.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@invertase/react-native-google-ads/v/3.0.0)
- [GitHub release](https://github.com/invertase/react-native-google-ads/releases/tag/v3.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: