[WIP] TS rewrite
invertase/react-native-google-ads pull request #41
Opened 2021-12-14 12:16 UTC by dylancom

141 ts errors to go.

2021-12-14 12:40 UTC, mikehardy commented
99 problems but weak typing isn't one

2021-12-17 14:39 UTC, mikehardy commented on src/types/AdsConsent.interface.ts
> +   * Emulators are automatically whitelisted and should require no action.
```suggestion
   * Emulators are automatically on the allowlist and should require no action.
```

google's got a nifty inclusive language filter which makes it trivial to perform what is really one of the more basic gestures of inclusiveness, so I always act on it

2021-12-17 14:39 UTC, mikehardy commented on src/types/RequestConfiguration.ts
> +   * An array of test device IDs to whitelist.
```suggestion
   * An array of test device IDs to add to the allowlist.
```

2021-12-17 15:08 UTC, mikehardy requested changes
First of all, this is amazing. Typescript is clearly the way to go and I am really excited for this.

Second, I have at this point too many decades of experience programming to admit, but I only have a year or so of heavy typescript and no real focus on typing from scratch. Combine the two and sometimes I'm right on the mark with serious issues and sometimes I'm just missing something completely and need an explanation like for a young child :-). Apologies in advance for any young child bits :baby: 

Third, I am of the opinion that in general those doing the work get the last say, and in general you should stay out of their way. Which gives me a strong bias for incremental improvement, light discussion, and merging - relying on the submitter to hold themselves to high standards (which you do, by the way - just stating my style)

So with all that said, I saw some things and I noted some things. And I think with a little discussion they will either be obvious to me, or they will result in improvements, and then without too much fuss we'll merge this and boom, we'll be in typescript.

Thanks!

2021-12-17 15:08 UTC, mikehardy commented on src/types/AdEventListener.ts
> +  data?: any | RewardedAdReward,
is it really any?

2021-12-17 15:08 UTC, mikehardy commented on src/types/AdsConsent.interface.ts
> +export interface AdsConsentStatus {
weren't these also an enum? the interface and enum feels somehow duplicate to me - are both required?

2021-12-17 15:08 UTC, mikehardy commented on src/types/AdsConsent.interface.ts
> +      | AdsConsentDebugGeography['DISABLED']
doesn't indexing in via string defeat the type, why not `AdsConsentDebugGeography.DISABLED` ?

2021-12-17 15:08 UTC, mikehardy commented on src/types/MobileAdsModule.ts
> +  emitter: any;
would be nice to have a real type

2021-12-17 15:08 UTC, mikehardy commented on src/types/MobileAdsModule.ts
> +  status: 0 | 1;
what do the 0 and 1 mean, semantically? Would be nice to have an enum that conveyed semantic meaning in a human way

2021-12-17 15:08 UTC, mikehardy commented on src/validateAdRequestOptions.ts
> +  if (typeof options === 'undefined') {
is this equivalent to 
```suggestion
  if (options === undefined) {
```
:thinking:

2021-12-17 15:08 UTC, mikehardy commented on src/validateAdShowOptions.ts
> +  if (typeof options === 'undefined') {
same === undefined question

2022-01-06 21:44 UTC, mikehardy approved these changes
Looks great - I don't see any reason to stand in the way

My only tiny thought is I have a slight preference to continue disallowing any and then using a ts-ignore very judiciously when necessary, so that any's don't creep in. And ts-ignores should be in a lint check for eventual fixing + removal. But then you could also say, just have a list of anys (along with ts-ignores) in a lint check for removal and then add the any lint rule back. It's kind of the same, so it's a small thought - and in the end it is not actionable

I'll see if I can get this packed up as a beta release now so it's easy to install it for testing to make sure the packaging is alright

2022-01-06 21:50 UTC, merged

2022-01-06 21:56 UTC, mikehardy commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@invertase/react-native-google-ads/v/4.0.0)
- [GitHub release](https://github.com/invertase/react-native-google-ads/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-01-06 22:04 UTC, mikehardy commented
Well, I got part of what I wanted. We safely have a release that is a major version (v4) and is tagged "beta" on npmjs.com, so "latest" is still the prior v3 version.

That's all good, that's safe.

However, for some reason - and unlike react-native-fbsdk-next when I did it, it got the npmjs.com release label right but it did not tag the release version itself in package.json as '-beta1'. Why? I don't know. But version 4.0.0 is "burnt" / used, so whenever this actually releases - if we need changes - it will be as 4.0.1 or something.

Not a big deal but it's odd, and I wish it had -beta1 in the version name. But I can't figure out why it didn't and in general I don't like beta releases, I prefer testing and then just "release" releases ;-), so I gave it a short timebox to figure it out and came empty and I'm leaving it for now

It's out! :-)

2022-01-06 22:08 UTC, mikehardy commented
@Mikenso + @birdofpreyru if you have a chance, your help testing v4.0.0 would be appreciated. It is currently on the `@beta` label in npmjs.com, so you have to install it specifically via version or via beta tag. The goal is to release this in a week or so if it seems fine, but it would be great to hear real success reports (or failure reports!). Thanks for your past help here and thanks in advance if you get a chance to check v4. Cheers

2022-01-09 12:03 UTC, birdofpreyru commented
Hey @mikehardy , I am a bit busy with different stuff now. Time allowing, I'll probably give it a try second half ot this week.

2022-01-11 16:31 UTC, Mikenso commented
Hi @mikehardy, I would like to test as soon as I will have free time. 
But from quick look - It is pleasure to see **dylancom** got rid from many default exports, I never understood people's love for them

2022-01-16 14:50 UTC, Mikenso commented
I have tested interstitial and banner at my current project written with ts.
And also checked at just created for test purposes raw js project.
It seems to work as it were at current stable version.

2022-01-16 17:14 UTC, mikehardy commented
Fantastic! Thanks very much for the feedback @Mikenso